/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package presentacion;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JDesktopPane;

/**
 *
 * @author DANY
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                g.setColor(Color.white);
                g.fillRect(0,0, getWidth(), getHeight());
            }
        };
        menuBar = new javax.swing.JMenuBar();
        mnuInformacion = new javax.swing.JMenu();
        mnuContactos = new javax.swing.JMenuItem();
        mnuRedesSociales = new javax.swing.JMenuItem();
        mnuSitio = new javax.swing.JMenu();
        mnuSitioHotel = new javax.swing.JMenuItem();
        mnuReservas = new javax.swing.JMenu();
        mnuReservar = new javax.swing.JMenuItem();
        mnuHabitaciones = new javax.swing.JMenuItem();
        mnuRegistros = new javax.swing.JMenu();
        mnuRegistrar = new javax.swing.JMenuItem();
        mnuIniciar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem8.setText("jMenuItem8");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(255, 255, 255));

        menuBar.setBorder(null);
        menuBar.setPreferredSize(new java.awt.Dimension(326, 50));

        mnuInformacion.setText("Mas informacion");
        mnuInformacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuInformacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuContactos.setText("Contactos");
        mnuContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuInformacion.add(mnuContactos);

        mnuRedesSociales.setText("Redes Sociales");
        mnuRedesSociales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuInformacion.add(mnuRedesSociales);

        menuBar.add(mnuInformacion);

        mnuSitio.setText("Sitio");
        mnuSitio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuSitio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuSitioHotel.setText("Sitio Hotel");
        mnuSitioHotel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuSitio.add(mnuSitioHotel);

        menuBar.add(mnuSitio);

        mnuReservas.setText("Reservas");
        mnuReservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuReservas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuReservar.setText("Reservas");
        mnuReservar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReservarActionPerformed(evt);
            }
        });
        mnuReservas.add(mnuReservar);

        mnuHabitaciones.setText("Habitaciones");
        mnuHabitaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHabitacionesActionPerformed(evt);
            }
        });
        mnuReservas.add(mnuHabitaciones);

        menuBar.add(mnuReservas);

        mnuRegistros.setText("Registros");
        mnuRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mnuRegistrar.setText("Registrar");
        mnuRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarActionPerformed(evt);
            }
        });
        mnuRegistros.add(mnuRegistrar);

        mnuIniciar.setText("Iniciar");
        mnuIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIniciarActionPerformed(evt);
            }
        });
        mnuRegistros.add(mnuIniciar);

        menuBar.add(mnuRegistros);

        jMenu5.setBorder(null);
        jMenu5.setText("Salir");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem9.setText("Cerrar programa");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        menuBar.add(jMenu5);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIniciarActionPerformed
        FrmCliente frm = new FrmCliente();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
        (escritorio.getWidth() - frm.getWidth()) / 2,
        (escritorio.getHeight() - frm.getHeight()) / 2
        );
    }//GEN-LAST:event_mnuIniciarActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // COdigo
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRegistrarActionPerformed

    private void mnuHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHabitacionesActionPerformed
        
        FrmHabitacion frm = new FrmHabitacion();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
        (escritorio.getWidth() - frm.getWidth()) / 2,
        (escritorio.getHeight() - frm.getHeight()) / 2
        );
        
    }//GEN-LAST:event_mnuHabitacionesActionPerformed
        
    private void mnuReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReservarActionPerformed
        
        FrmReserva frm = new FrmReserva(escritorio);
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
        (escritorio.getWidth() - frm.getWidth()) / 2,
        (escritorio.getHeight() - frm.getHeight()) / 2
        );
        
    }//GEN-LAST:event_mnuReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuContactos;
    private javax.swing.JMenuItem mnuHabitaciones;
    private javax.swing.JMenu mnuInformacion;
    private javax.swing.JMenuItem mnuIniciar;
    private javax.swing.JMenuItem mnuRedesSociales;
    private javax.swing.JMenuItem mnuRegistrar;
    private javax.swing.JMenu mnuRegistros;
    private javax.swing.JMenuItem mnuReservar;
    private javax.swing.JMenu mnuReservas;
    private javax.swing.JMenu mnuSitio;
    private javax.swing.JMenuItem mnuSitioHotel;
    // End of variables declaration//GEN-END:variables

}
