/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;
import negocio.AdministradorControl;
import negocio.ClienteControl;
import negocio.RecepcionistaControl;

/**
 *
 * @author DANY
 */
public class PanelRegistro extends javax.swing.JPanel {
    private final ClienteControl CONTROLCLIENTE;
    private final RecepcionistaControl CONTROLRECEPCIONISTAS;
    private final AdministradorControl CONTROLADMINISTRADOR;
    
    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro() {
        initComponents();
        this.CONTROLCLIENTE = new ClienteControl();
        this.CONTROLRECEPCIONISTAS = new RecepcionistaControl();
        this.CONTROLADMINISTRADOR = new AdministradorControl();
    }
    
    private void limpiar(){
        txtNombre.setText("");
        txtTelefono.setText("");
        txtDocumento.setText("");
    }
    
    private void listar(String texto){
        
    }
    
    private void mensajeError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }
    
    private void mensajeOK(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnTipoRegistro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDatosRegistro = new javax.swing.JComboBox<>();
        lbDatos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("REGISTRATE EN EL SISTEMA ");

        jLabel2.setText("Nombre (*)");

        jLabel3.setText("Telefono (*)");

        jLabel4.setText("Documento (*)");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        btnTipoRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Recepcionista", "Administrador" }));
        btnTipoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoRegistroActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de registro (*)");

        jLabel6.setText("(*) Indica que es un campo obligatorio");

        btnDatosRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estandar", "VIP" }));
        btnDatosRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosRegistroActionPerformed(evt);
            }
        });

        lbDatos.setText("Tipo de cliente:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDocumento)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtNombre)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbDatos)
                                .addComponent(btnDatosRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbDatos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatosRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoRegistroActionPerformed
        String opcion = btnTipoRegistro.getSelectedItem().toString();
        
        btnDatosRegistro.removeAllItems();
        
        if(opcion.equals("Cliente")) {
            btnDatosRegistro.addItem("Estandar");
            btnDatosRegistro.addItem("VIP");
            lbDatos.setText("Tipo de cliente:");
        } else if(opcion.equals("Recepcionista")) {
            btnDatosRegistro.addItem("De dia");
            btnDatosRegistro.addItem("De noche");
            lbDatos.setText("Turno:");
        } else if(opcion.equals("Administrador")) {
            btnDatosRegistro.addItem("General");
            lbDatos.setText("Cargo:");
        }
            
    }//GEN-LAST:event_btnTipoRegistroActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Nombre es obligatorio, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return;
        }else if(txtTelefono.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Telefono, de 10 caracteres, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
            txtTelefono.requestFocus();
            return;
        }else if(txtDocumento.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Documento de 10 caracteres, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
            txtDocumento.requestFocus();
            return;
        }else if(txtDocumento.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Debes ingresar un Documento de 10 caracteres, es obligatorio", "Sistema", JOptionPane.WARNING_MESSAGE);
            txtDocumento.requestFocus();
            return;
        }
        
        String opcion = btnTipoRegistro.getSelectedItem().toString();
        String resp;
        
        if (opcion.equals("Cliente")) {
            boolean tipoCliente = btnDatosRegistro.getSelectedItem().toString().equals("Estandar");
            
            resp = this.CONTROLCLIENTE.insertar(txtNombre.getText(), txtTelefono.getText(), txtDocumento.getText(), tipoCliente);
            if (resp.equals("OK")) {
                this.mensajeOK("Registrado cliente correctamente");
                this.limpiar();
                this.listar("");
            }else{
                this.mensajeError(resp);
            }
        } else if (opcion.equals("Recepcionista")) {
            boolean turno = btnDatosRegistro.getSelectedItem().toString().equals("De dia");
            resp = this.CONTROLRECEPCIONISTAS.insertar(txtNombre.getText(), txtTelefono.getText(), txtDocumento.getText(), turno);
            if (resp.equals("OK")) {
                this.mensajeOK("Registrado recepcionista correctamente");
                this.limpiar();
                this.listar("");
            }else{
                this.mensajeError(resp);
            }
        } else if(opcion.equals("Administrador")){
            boolean cargo = btnDatosRegistro.getSelectedItem().toString().equals("General");
            resp = this.CONTROLADMINISTRADOR.insertar(txtNombre.getText(), txtTelefono.getText(), txtDocumento.getText(), cargo);
            if (resp.equals("OK")) {
                this.mensajeOK("Registrado recepcionista correctamente");
                this.limpiar();
                this.listar("");
            }else{
                this.mensajeError(resp);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el tipo de registro", "Sistema", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnDatosRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosRegistroActionPerformed
        
    }//GEN-LAST:event_btnDatosRegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> btnDatosRegistro;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> btnTipoRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbDatos;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
